version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: vts-postgres
    restart: always
    environment:
      POSTGRES_DB: vts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vts123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: vts-mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  redis:
    image: redis:7-alpine
    container_name: vts-redis
    restart: always
    ports:
      - "6379:6379"

  temporal:
    image: temporalio/auto-setup:1.23
    container_name: vts-temporal
    restart: always
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=vts123
      - POSTGRES_SEEDS=postgres

  temporal-ui:
    image: temporalio/ui:latest
    container_name: vts-temporal-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:

# #for public release
# version: '3.9'

# services:

#   backend:
#     build: .
#     container_name: vts-backend
#     restart: always
#     ports:
#       - "3000:3000"

#     depends_on:
#       - postgres
#       - redis
#       - mosquitto
#       - temporal

#     env_file:
#       - .env.docker

#     environment:
#       NODE_ENV: development
#       PORT: 3000

#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_NAME: vts
#       DB_USER: postgres
#       DB_PASSWORD: vts123

#       MQTT_BROKER_URL: mqtt://mosquitto:1883
#       MQTT_TELEMETRY_TOPIC: vts/devices/+/telemetry

#       TEMPORAL_ADDRESS: temporal:7233
#       REDIS_HOST: redis
#       REDIS_PORT: 6379

#     healthcheck:
#       test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', res => process.exit(res.statusCode === 200 ? 0 : 1))"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

#   postgres:
#     image: postgres:15
#     container_name: vts-postgres
#     restart: always
#     environment:
#       POSTGRES_DB: vts
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: vts123
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   mosquitto:
#     image: eclipse-mosquitto:2
#     container_name: mosquitto
#     restart: always
#     ports:
#       - "1883:1883"
#       - "9001:9001"
#     volumes:
#       - mosquitto_data:/mosquitto/data
#       - mosquitto_log:/mosquitto/log

#   redis:
#     image: redis:7-alpine
#     container_name: vts-redis
#     restart: always
#     ports:
#       - "6379:6379"

#   temporal:
#     image: temporalio/auto-setup:1.23
#     container_name: vts-temporal
#     restart: always
#     ports:
#       - "7233:7233"
#     environment:
#       DB: postgresql
#       DB_PORT: 5432
#       POSTGRES_USER: postgres
#       POSTGRES_PWD: vts123
#       POSTGRES_SEEDS: postgres

#   temporal-ui:
#     image: temporalio/ui:latest
#     container_name: vts-temporal-ui
#     restart: always
#     ports:
#       - "8080:8080"
#     environment:
#       TEMPORAL_ADDRESS: temporal:7233
#     depends_on:
#       - temporal

# volumes:
#   postgres_data:
#   mosquitto_data:
#   mosquitto_log: